enable:
  issues: true
  prs: true

labels:
  '🎸 Chore':
    - '^chore/'
  '🔗 CI/CD':
    - '^ci/'
    - '^cd/'
  '🎨 Design':
    - '^design/'
  '📃 Docs':
    - '^docs/'
  '🛠️ Feature':
    - '^feat/'
  '🔧 Fix':
    - '^fix/'
  '🪄 Refactor':
    - '^refactor/'
  '⚙️ Setting':
    - '^setting/'
  '🌈 Deploy':
    - '^deploy/'
  '🧩 Test':
    - '^test/'
