name: Auto Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Label and assign by author
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.payload.pull_request.user.login;

            const config = {
              'heesunee': { label: '희선', assign: 'heesunee' },
              'constantly-dev': { label: '진혁', assign: 'constantly-dev' },
              'hansoojeongsj': { label: '수정', assign: 'hansoojeongsj' },
              'KIMGEONHWI': { label: '건휘', assign: 'KIMGEONHWI' },
              'rtttr1': { label: '규홍', assign: 'rtttr1' }
            };

            const data = config[author];
            if (data) {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [data.label],
              });

              await github.rest.issues.addAssignees({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees: [data.assign],
              });
            }
